<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.*" />
    <PackageReference Include="MediatR" Version="12.*" />
    <PackageReference Include="MassTransit" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Order.Domain\Order.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Ecommerce.Contracts\Ecommerce.Contracts.csproj" />
  </ItemGroup>

</Project>
