apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - env:
        - name: RabbitMQ__Host
          value: rabbitmq
        - name: OpenTelemetry__Endpoint
          value: http://otel-collector.monitoring.svc.cluster.local:4317
        envFrom:
        - configMapRef:
            name: order-api-config
        - secretRef:
            name: order-db-credentials
        - secretRef:
            name: rabbitmq-credentials
        image: localhost/ecommerce/order-api:1.0.0-30e7e62
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 15
          timeoutSeconds: 5
        name: order-api
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 24
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 750m
            memory: 384Mi
          requests:
            cpu: 200m
            memory: 192Mi
      initContainers:
      - command:
        - /bin/bash
        - -c
        - echo 'Waiting for order-db-rw:5432 (TCP)...' && until (echo > /dev/tcp/order-db-rw/5432)
          2>/dev/null; do sleep 1; done && echo 'order-db-rw TCP ready. Waiting for
          RabbitMQ:5672 (TCP)...' && until (echo > /dev/tcp/rabbitmq/5672) 2>/dev/null;
          do sleep 1; done && echo 'All dependencies TCP-ready.'
        image: postgres:16-alpine
        name: wait-for-dependencies
