apiVersion: v1
data:
  OpenTelemetry__Endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
  ReverseProxy__Clusters__inventory-cluster__Destinations__inventory-api__Address: http://inventory-api:8080
  ReverseProxy__Clusters__order-cluster__Destinations__order-api__Address: http://order-api:8080
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: ecommerce
